name: .NET API CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0' 

    - name: Restore dependencies
      run: dotnet restore path/to/your/api/project/**/*.csproj

    - name: Build
      run: dotnet build path/to/your/api/project/**/*.csproj --configuration Release --no-restore

    - name: Run tests
      run: dotnet test **/*Tests.csproj --configuration Release --no-build

    - name: Build Docker Image
      run: docker build -t your-image-repository:$GITHUB_RUN_ID ./NG.API/DockerFile

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Push Docker Image
      run: docker push your-image-repository:$GITHUB_RUN_ID
