name: Terraform CI/CD

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  terraform_ci:
    name: 'Terraform CI'
    runs-on: ubuntu-latest
    # This job runs automatically on pull_request and push events to main branch.
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2
    
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: latest

    - name: Terraform Init
      run: terraform init
      working-directory: ./terraform
      env:
        ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
        ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
        ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
        SQL_SERVER_LOGIN: ${{ secrets.SQL_SERVER_LOGIN }}
        SQL_SERVER_PASSWORD: ${{ secrets.SQL_SERVER_PASSWORD }}
        
    - name: Terraform Validate
      run: terraform validate
      working-directory: ./terraform
      env:
        ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
        ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
        ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
        SQL_SERVER_LOGIN: ${{ secrets.SQL_SERVER_LOGIN }}
        SQL_SERVER_PASSWORD: ${{ secrets.SQL_SERVER_PASSWORD }}

    - name: Terraform Plan
      run: terraform plan
      working-directory: ./terraform
      env:
        ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
        ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
        ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
        SQL_SERVER_LOGIN: ${{ secrets.SQL_SERVER_LOGIN }}
        SQL_SERVER_PASSWORD: ${{ secrets.SQL_SERVER_PASSWORD }}

  terraform_cd:
    name: 'Terraform CD'
    runs-on: ubuntu-latest
    needs: terraform_ci
    if: ${{ github.event_name == 'workflow_dispatch' }}
    # This job requires a manual trigger.
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2
    
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: latest

    - name: Terraform Init
      run: terraform init
      working-directory: ./terraform

    - name: Terraform Apply
      run: terraform apply -auto-approve
      working-directory: ./terraform
      env:
        ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
        ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
        ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
        SQL_SERVER_LOGIN: ${{ secrets.SQL_SERVER_LOGIN }}
        SQL_SERVER_PASSWORD: ${{ secrets.SQL_SERVER_PASSWORD }}
