name: Terraform CI/CD

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  terraform_ci:
    name: 'Terraform CI'
    runs-on: ubuntu-latest
    env:
      TF_VAR_subscription_id: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      TF_VAR_client_id: ${{ secrets.ARM_CLIENT_ID }}
      TF_VAR_client_secret: ${{ secrets.ARM_CLIENT_SECRET }}
      TF_VAR_tenant_id: ${{ secrets.ARM_TENANT_ID }}
      TF_VAR_sql_server_login: ${{ secrets.SQL_SERVER_LOGIN }}
      TF_VAR_sql_server_login_password: ${{ secrets.SQL_SERVER_PASSWORD }}
    # This job runs automatically on pull_request and push events to main branch.
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2
    
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: latest

    - name: Terraform Init
      run: terraform init
      working-directory: ./terraform
        
    - name: Terraform Validate
      run: terraform validate
      working-directory: ./terraform

    - name: Terraform Plan
      run: terraform plan
      working-directory: ./terraform

  terraform_cd:
    name: 'Terraform CD'
    runs-on: ubuntu-latest
    needs: terraform_ci
    if: ${{ github.event_name == 'workflow_dispatch' }}
    # This job requires a manual trigger.
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2
    
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: latest

    - name: Terraform Init
      run: terraform init
      working-directory: ./terraform

    - name: Terraform Apply
      run: terraform apply -auto-approve
      working-directory: ./terraform
